name: ADH Lists - Daily Task

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'dontobi/AdGuardHome-Lists'
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Run Shell Script
        id: script
        run: |
          mkdir output
          cp whitelist.txt ./output
          chmod +x ./build_blacklist.sh
          sh ./build_blacklist.sh
          cp blacklist.txt ./output
        shell: bash

      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3.2.0
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.2.0
        with:
          target_branch: lists
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
