name: ADH Lists - Daily Task

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: 'dontobi/AdGuardHome-Lists'
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Run Shell Script
        id: script
        run: |
          mkdir output
          cp blacklist.txt whitelist.txt ./output
          chmod +x ./experimental.sh
          sh ./experimental.sh
          cp experimental.txt ./output
        shell: bash

      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2.2.0
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: lists
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
